CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=y

# The Thingy:53 MCUboot config enables a serial-recovery command that erases
# the "storage" partition; this layout has no storage partition.
CONFIG_BOOT_MGMT_CUSTOM_STORAGE_ERASE=n
